### ISSUE TITLE
Prometheus exporter URL has no auth

### ISSUE THREAD

**Issue by lgarvey** [alphagov/paas-cf-apps-statsd#28]
Just wondering how you are protecting the prometheus exporter URL, if at all?

I know the typical prometheus guideline is to use something like nginx to handle basic auth, but that's not so straight forward in the Paas.

**Comment by keymon** [comment]
Good point. 

One can setup a route service as it is described here: https://docs.cloud.service.gov.uk/deploying_services.html#example-route-service-to-add-authentication

Other option is to implement basic auth in this application itself, for instance by adding a library like https://github.com/abbot/go-http-auth [into the controller](https://github.com/alphagov/paas-metric-exporter/blob/18d25e2a3aa0fcd4fc43177d23261e4947a67752/app/app.go#L137-L138)

**Comment by lgarvey** [comment]
I modded the DIT exporter to add basic auth, but using a route service app seems like a better option.

Thanks! 👍

**Comment by keymon** [comment]
@lgarvey a PR with the basic auth mod would be also welcome! :) 

I guess it can be set using some env vars.

**Comment by lgarvey** [comment]
OK, cool - I'll get that done :)

Also, I'm about to test your metric exporter PR.
